  withname: Clojure CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
# 2. Set permissions
# The 'contents: write' permission is required to create a release
permissions:
  contents: write

jobs:
  buil-uberjar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v5.0.0
        distribution: 'microsoft'
        java-version: '21'
      - uses: DeLaGuardo/setup-clojure@13.4
        with:
          lein: 2.10
      - name: build uberjar
        run: lein uberjar 
